<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">


        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                        ->prependStylesheet($this->basePath('css/isteven-multi-select.css')) ?>

        <!-- Scripts -->
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular.min.js"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.5/angular-resource.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular-animate.js"></script>
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/app.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/isteven-multi-select.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>


    </head>

    <body ng-app="myApp" >
    <div>
        <!-- Menu -->
        <div id="topnav" class="topnav">
            <div style="padding :5px;">
                <?php if($this->identity ) : ?>
                    <a href="/" style="color : rgb(0, 16, 140);">Dashboard</a> - 
                    <a href="/auth/logout" style="color : rgb(0, 16, 140);">Logout</a>
                <?php else: ?>        
                    <a href="/auth/register" style="color : rgb(0, 16, 140);">Login</a> - 
                    <a href="/auth/register" style="color : rgb(0, 16, 140);">Register</a>
                <?php endif; ?>

            </div>
            <button type="button" class="myButton" style="position: absolute; top:0px ; right: 10px;" ng-click="modalShown=true;">Story</button> 
            <button type="button" class="myButton"  style="position: absolute; top:0px;right: 100px;" ng-click="delete_selected_facts()">✓&nbsp;&nbsp;Delete</button>
        </div>
        <!-- End Menu -->

    </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>

            </footer>
        </div> <!-- /container -->
        <?php //echo $this->inlineScript() ?>
    </body>
</html>
