<script type="text/javascript" src="http://etoolset.localhost/api/3VJJW0V96DEOTN6KESO7UW/FD0UXBQBOIGJSYNHRVVUXA"></script>
<script type="text/javascript">
function hi(){
    alert("hi");
}
app.directive('modalDialog', function() {
  return {
    restrict: 'E',
    scope: {
      show: '='
    },
    replace: true, // Replace with the template below
    transclude: true, // we want to insert custom content inside the directive
    link: function(scope, element, attrs) {
      scope.dialogStyle = {};
      if (attrs.width)
        scope.dialogStyle.width = attrs.width;
      if (attrs.height)
        scope.dialogStyle.height = attrs.height;
      scope.hideModal = function() {
        console.log("hide called!");
        scope.show = false;
      };
    },
    template: "<div class='ng-modal' ng-show='show'><div class='ng-modal-overlay' ng-click='hideModal()'></div><div class='ng-modal-dialog' ng-style='dialogStyle'><div class='ng-modal-dialog-content' ng-transclude></div></div></div>"
  };
});

app.controller('MainCtrl',  ['$scope','$http', '$interval' , function ($scope, $http , $interval) {
    $scope.modalShown = false;

    $scope.content = 'Hello World';
    $scope.general_tags =  [];
    $scope.facts = []; 
    $scope.intersection_facts = []; 

    $http.post('/rest/tag', { 'task':'get_all_tags'}).then(
        function(response) {
            $scope.general_tags = response.data.list;
            console.log(response.data.list);
        }
    )

    $http.post('/rest/fact', { 'task':'get_all_intersection_facts', 'selected_tags': $scope.output_general_tags}).then(
        function(response) {
            $scope.intersection_facts = response.data.list;
            console.log(response.data.list);
        }
    )

    $http.post('/rest/fact', { 'task':'get_all_facts', 'selected_tags': $scope.output_general_tags}).then(
        function(response) {
            $scope.facts = response.data.list;
            console.log(response.data.list);
        }
    )

    $scope.add_new_tag = function(new_tag){
        // console.log(new_tag);
        $http.post('/rest/tag', { 'task':'add_new_tag', 'new_tag':new_tag }).then(
                                function(response) {
                                    $scope.general_tags = response.data.list;
                                    console.log(response.data.list);
                                }
                          );
    }
    $scope.add_new_fact = function(new_fact){
        console.log(new_fact);
        $http.post('/rest/fact', { 'task':'add_new_fact', 'new_fact':new_fact , 'selected_tags': $scope.output_general_tags }).then(
                                function(response) {
                                    // if(response.data.list['msg'] ) alert(response.data.list['msg'] );
                                    // else{
                                        $scope.facts = response.data.list;
                                        console.log(response.data.list);
                                        $scope.modalShown = false ; 
                                    // }
                                }
                          );
    }

    $scope.get_all_facts = function(){
        console.log();
        $http.post('/rest/fact', { 'task':'get_all_facts', 'selected_tags': $scope.output_general_tags }).then(
                                function(response) {
                                    // if(response.data.list['msg'] ) alert(response.data.list['msg'] );
                                    // else{
                                        $scope.facts = response.data.list;
                                        console.log(response.data.list);
                                    // }
                                }
                          );
    }

    $scope.get_all_intersection_facts = function(){
        console.log();
        $http.post('/rest/fact', { 'task':'get_all_intersection_facts', 'selected_tags': $scope.output_general_tags}).then(
            function(response) {
                $scope.intersection_facts = response.data.list;
                console.log(response.data.list);
            }
        )
    }


    $scope.delete_selected_tags = function(){
        console.log($scope.output_general_tags);
        $http.post('/rest/tag', { 'task':'delete_selected_tags', 'selected_tags': $scope.output_general_tags }).then(
                                function(response) {
                                    $scope.general_tags = response.data.list;
                                    console.log(response.data.list);
                                }
                          );
    }
    $scope.delete_selected_facts = function(){
        console.log($scope.output_general_tags);
        $http.post('/rest/fact', { 'task':'delete_selected_facts', 'selected_tags': $scope.output_general_tags, 'selected_facts': $scope.output_facts }).then(
                                function(response) {
                                    $scope.facts = response.data.list;
                                    console.log(response.data.list);
                                }
                          );
    }
}]);


    angular.module('mc.resizer', []).directive('resizer', function($document) {

    return function($scope, $element, $attrs) {

        $element.on('mousedown', function(event) {
            event.preventDefault();

            $document.on('mousemove', mousemove);
            $document.on('mouseup', mouseup);
        });

        function mousemove(event) {

            if ($attrs.resizer == 'vertical') {
                // Handle vertical resizer
                var x = event.pageX;

                if ($attrs.resizerMax && x > $attrs.resizerMax) {
                    x = parseInt($attrs.resizerMax);
                }

                $element.css({
                    left: x + 'px'
                });

                $($attrs.resizerLeft).css({
                    width: x + 'px'
                });
                $($attrs.resizerRight).css({
                    left: (x + parseInt($attrs.resizerWidth)) + 'px'
                });

            } else {
                // Handle horizontal resizer
                var y = window.innerHeight - event.pageY;

                $element.css({
                    bottom: y + 'px'
                });

                $($attrs.resizerTop).css({
                    bottom: (y + parseInt($attrs.resizerHeight)) + 'px'
                });
                $($attrs.resizerBottom).css({
                    height: y + 'px'
                });
            }
        }

        function mouseup() {
            $document.unbind('mousemove', mousemove);
            $document.unbind('mouseup', mouseup);
        }
    };
});

</script>

    
<div ng-controller="MainCtrl">

    <!-- NEW STORY POP-UP -->
    <modal-dialog show='modalShown' width='840px' height='586px'>
        <div style="position: absolute; top :4px; bottom:4px; left: 4px;  ">
            <div style="height: 100%; overflow-y:auto; width: 293px; ">
                <div isteven-multi-select
                        input-model="general_tags"
                        output-model="output_tags_new_fact"
                        button-label="icon name"
                        item-label="icon name maker"
                        tick-property="ticked">       
                </div> 
            </div>
        </div>
        <div style="top: 2px; bottom: 67px; left: 300px; right: 2px; position: absolute;">
            <textarea ng-model="new_fact" style="resize: none; width: 100%; height: 100%; "></textarea>
        </div>
        <button class="btn btn-primary btn-lg gradient"  style="position: absolute; right: 10px; bottom: 12px;" type="button" class="clearButton" ng-click="add_new_fact(new_fact)">Story</button> 

    </modal-dialog>

   
   <!-- GENERAL TAGS  -->
    <div id="sidebar" class="left">
        <div id="top-" class="top" style="height: 100%;"> 
            <div   class="top"  style="top:26px; bottom: 0px; ">
                <div     
                isteven-multi-select
                input-model="general_tags"
                output-model="output_general_tags"
                button-label="icon name"
                item-label="icon name maker"
                tick-property="ticked">       
                </div> 
            </div>
            <div style="height:35px; bottom: 0px; background-color: white;">
                <div class="line ng-scope" style="position:inherit; bottom: 3px;" >
                <input ng-model="new_tag" placeholder="New tag.." class="inputFilter ng-pristine ng-valid ng-empty ng-touched" type="text"> 
                <button type="button" class="clearButton" ng-click="add_new_tag(new_tag)"> ADD</button> 
                <button type="button" class="helperButton ng-binding ng-scope" ng-click="delete_selected_tags()">✓&nbsp;&nbsp;Delete</button>
                <button type="button" class="clearButton" ng-click="get_all_facts();get_all_intersection_facts();"> Refresh</button> 
                </div>
            </div>
        </div>

    </div>
  
    <div id="content" class="right">

        <div id="top-content" class="top">
            <div isteven-multi-select
                    input-model="facts"
                    output-model="output_facts"
                    button-label="icon name"
                    item-label="icon name maker"
                    tick-property="ticked">       
            </div> 

       <!--      <div class="line ng-scope" style="position:inherit; bottom: 3px;" >
            </div>
 -->
        </div>
  
        <div id="bottom-content" class="down">
            <div     
            isteven-multi-select
            input-model="intersection_facts"
            output-model="output_intersection_facts"
            button-label="icon name"
            item-label="icon name maker"
            tick-property="ticked">       

            </div> 
        </div>
  
        <div id="content-resizer" class="content-resizer" 
            resizer="horizontal" 
            resizer-height="6" 
            resizer-top="#top-content" 
            resizer-bottom="#bottom-content">
        </div>
    </div>
  
    <div id="sidebar-resizer" class="sidebar-resizer" 
        resizer="vertical" 
        resizer-width="6" 
        resizer-left="#sidebar" 
        resizer-right="#content"
        resizer-max="400">
    </div>
    </div>